import { notFound } from 'next/navigation' // triggers Next.js 404 response
import type { Metadata } from 'next' // return type for generateMetadata
import Link from 'next/link' // Next.js client-side navigation link
import { loadHighPrioritySlugs, loadPageBySlug, loadAllPageMeta } from '@/lib/pages' // content loaders

// Allow Next.js to render slugs not in generateStaticParams on-demand (ISR)
// Without this, unknown slugs would 404 at the router level rather than falling through to SlugPage
export const dynamicParams = true

// Cache on-demand (non-pre-built) pages for 24 hours via ISR
// Pre-built high-priority pages are always static and unaffected by this setting
export const revalidate = 86400

// Pre-build only high-priority page types at deploy time (~56 pages)
// Combinatorial/lower-priority types (~134 pages) render on first request and are ISR-cached
export function generateStaticParams(): { slug: string }[] {
  return loadHighPrioritySlugs().map(slug => ({ slug })) // each slug maps to one pre-built HTML file
}

// Generate <title> and <meta description> from the page's own frontmatter
export async function generateMetadata({
  params,
}: {
  params: { slug: string }
}): Promise<Metadata> {
  const page = loadPageBySlug(params.slug) // load the page to read its frontmatter
  if (!page) return { title: 'Not Found' } // graceful fallback for missing pages
  return {
    title: page.title, // fills the '%s' slot in the root layout template
    description: page.description, // written into <meta name="description">
  }
}

// Individual content page — renders a generated markdown page by its slug
export default function SlugPage({ params }: { params: { slug: string } }) {
  const page = loadPageBySlug(params.slug) // fetch page data including rendered HTML
  if (!page) notFound() // trigger the nearest not-found boundary if slug is unknown

  // Build a slug → title map from all pages for related-page link resolution
  const allMeta = loadAllPageMeta() // load frontmatter for every generated page
  const titleBySlug = new Map(allMeta.map(m => [m.slug, m.title])) // O(1) title lookup by slug

  // Resolve related page titles from the slugs stored in frontmatter
  const relatedSlugs = page.relatedPages ?? [] // default to empty array if field is absent
  const relatedLinks = relatedSlugs
    .map(slug => ({ slug, title: titleBySlug.get(slug) })) // pair each slug with its title
    .filter((r): r is { slug: string; title: string } => r.title !== undefined) // drop any unresolvable slugs

  return (
    <article>
      {/* Page type label shown above the content as a breadcrumb hint */}
      <p style={{ color: '#888', fontSize: '0.8rem', margin: '0 0 0.25rem' }}>
        {page.pageType.replace(/-/g, ' ')} {/* "audience-category" → "audience category" */}
      </p>

      {/* Rendered markdown HTML — safe because content is generated by our own pipeline */}
      <div dangerouslySetInnerHTML={{ __html: page.html }} />

      {/* Related Pages section — only rendered when at least one related page exists */}
      {relatedLinks.length > 0 && (
        <section style={{ marginTop: '2rem' }}>
          <h2 style={{ fontSize: '1rem', color: '#333', borderBottom: '1px solid #eee', paddingBottom: '0.3rem' }}>
            Related Pages {/* heading for internal-link navigation block */}
          </h2>
          <ul style={{ listStyle: 'none', paddingLeft: 0, margin: '0.5rem 0 0' }}>
            {relatedLinks.map(r => (
              <li key={r.slug} style={{ marginBottom: '0.3rem' }}>
                <Link href={`/${r.slug}`} style={{ color: '#0070f3', textDecoration: 'none' }}>
                  {r.title} {/* display resolved title as link text */}
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Footer strip with navigation back to homepage and generation timestamp */}
      <hr style={{ marginTop: '2.5rem', borderColor: '#eee' }} />
      <p style={{ fontSize: '0.8rem', color: '#888' }}>
        <a href="/" style={{ color: '#0070f3' }}>
          ← All pages
        </a>
        {' · '}
        Generated {new Date(page.generatedAt).toLocaleDateString()} {/* human-readable date */}
      </p>
    </article>
  )
}
